# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestregistration1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testregistration1(self):
    self.driver.get("http://selenium1py.pythonanywhere.com/ru/accounts/login/")
    self.driver.set_window_size(1918, 1040)
    self.driver.find_element(By.ID, "id_registration-email").click()
    self.driver.find_element(By.ID, "id_registration-email").send_keys("blablablah1111@yandex.ru")
    element = self.driver.find_element(By.ID, "id_registration-email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "id_registration-email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "id_registration-email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "id_registration-email").click()
    self.driver.find_element(By.ID, "id_registration-email").send_keys("blablablah11311@yandex.ru")
    self.driver.find_element(By.ID, "id_registration-password1").click()
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("PasswordExample11")
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("PasswordExample11")
    self.driver.find_element(By.NAME, "registration_submit").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alertinner").text == "Спасибо за регистрацию!"
  
